schemaVersion: "2.0.0"

metadataTest:
  env:
    - key: "GF_PATHS_DATA"
      value: "/opt/grafana"
    - key: "GF_PATHS_PLUGINS"
      value: "/opt/plugins"

fileExistenceTests:
  - name: "entrypoint"
    path: "/entrypoint.sh"
    shouldExist: true
    permissions: "-rwxr-xr-x"
  - name: "run.sh"
    path: "/run.sh"
    shouldExist: true
    permissions: "-rwxr-xr-x"
  - name: "grafana.ini"
    path: "/etc/grafana/grafana.ini"
    shouldExist: true
    permissions: "-rw-r--r--"
  - name: "server.conf"
    path: "/etc/nginx/sites-enabled/grafana.conf"
    shouldExist: true
    permissions: "-rw-r--r--"

fileContentTests:
    - name: "Nginx conf"
      path: "/etc/nginx/sites-enabled/grafana.conf"
      expectedContents:
        [
            "listen 80 default_server;",
            "listen \\[::\\]:80 default_server",
            "location SAAGIE_BASE_PATH {",
            "proxy_pass http://localhost:3000;",
        ]

commandTests:
  - name: "Workdir"
    command: "pwd"
    expectedOutput: ["/usr/share/grafana"]
  - name: "nginx"
    command: "nginx"
    args: ["-h"]
    expectedOutput: ["nginx version:*"]
